
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Dec 20 23:45:29 CET 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 36;
  public static final int CONST = 17;
  public static final int LPAREN = 10;
  public static final int SEMI = 7;
  public static final int CONTINUE = 21;
  public static final int FOR = 20;
  public static final int MINUS = 24;
  public static final int NUMBERCONST = 44;
  public static final int RPAREN = 5;
  public static final int AND = 28;
  public static final int LS = 34;
  public static final int OR = 29;
  public static final int COMMA = 12;
  public static final int CLASS = 41;
  public static final int INC = 22;
  public static final int DIV = 26;
  public static final int GEQ = 33;
  public static final int PLUS = 3;
  public static final int ASSIGN = 6;
  public static final int IF = 9;
  public static final int DOT = 38;
  public static final int ABSTRACT = 42;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int RBRACKET = 37;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 25;
  public static final int MOD = 27;
  public static final int IDENT = 45;
  public static final int BREAK = 16;
  public static final int VOID = 15;
  public static final int EQ = 30;
  public static final int LBRACE = 11;
  public static final int ELSE = 2;
  public static final int READ = 19;
  public static final int CHARCONST = 40;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 43;
  public static final int BOOLCONST = 39;
  public static final int PROG = 13;
  public static final int LEQ = 35;
  public static final int DEC = 23;
  public static final int GR = 32;
  public static final int PRINT = 14;
  public static final int NOTEQ = 31;
}

